import { GenericService } from './../../core/services/generic.service'
import { Component, OnInit } from '@angular/core'
import { TreeTableModule } from 'primeng/treetable'
import { TreeNode } from 'primeng/api'

@Component({
  selector: 'app-listing-counter',
  templateUrl: './listing-counter.component.html',
  styleUrls: ['./listing-counter.component.scss'],
})
export class ListingCounterComponent implements OnInit {
  data = [
    {
      Id: 1,
      Name: 'Rack1_Pdu1_Energy',
      AlarmIds: [2],
      CoefDistribution: 100,
      CoefUnit: 1,
      Description: 'Description du compteur',
      Formula: '',
      LocationId: 5,
      ParentId: 17,
      RefFormula: '',
      RefSamplePeriod: 4,
      ServiceId: 1,
      TrendId: 1,
    },
    {
      Id: 2,
      Name: 'Rack1_Pdu2_Energy',
      CoefDistribution: 100,
      CoefUnit: 1,
      Description: '',
      Formula: '',
      LocationId: 6,
      ParentId: 1,
      RefFormula: '',
      RefSamplePeriod: 4,
      ServiceId: 1,
      TrendId: 2,
    },
    {
      Id: 10,
      Name: 'Office lighting',
      CoefDistribution: 100,
      CoefUnit: 1,
      Description: '',
      Formula: '',
      LocationId: 15,
      RefFormula: '',
      RefSamplePeriod: 4,
      ServiceId: 3,
      TrendId: 9,
    },
    {
      Id: 11,
      Name: 'Basement lighting',
      CoefDistribution: 100,
      CoefUnit: 0.5,
      Description: '',
      Formula: '',
      LocationId: 14,
      ParentId: 10,
      RefFormula: '',
      RefSamplePeriod: 4,
      ServiceId: 3,
      TrendId: 10,
    },
    {
      Id: 12,
      Name: 'Water',
      CoefDistribution: 100,
      CoefUnit: 0.01,
      Description: '',
      Formula: '',
      LocationId: 13,
      RefFormula: '',
      RefSamplePeriod: 4,
      ServiceId: 5,
      TrendId: 11,
    },
    {
      Id: 13,
      Name: 'Heating',
      CoefDistribution: 100,
      CoefUnit: 1,
      Description: 'Test',
      Formula: '',
      LocationId: 13,
      ParentId: 16,
      RefFormula: '',
      RefSamplePeriod: 4,
      ServiceId: 2,
      TrendId: 12,
    },
    {
      Id: 14,
      Name: 'Cooling',
      CoefDistribution: 100,
      CoefUnit: 1,
      Description: '',
      Formula: '',
      LocationId: 239,
      ParentId: 16,
      RefFormula: '',
      RefSamplePeriod: 4,
      ServiceId: 6,
      TrendId: 13,
    },
    {
      Id: 15,
      Name: 'Datacenter cooling',
      CoefDistribution: 100,
      CoefUnit: 3,
      Description: '',
      Formula: '',
      LocationId: 2,
      ParentId: 12,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 6,
      TrendId: 14,
    },
    {
      Id: 16,
      Name: 'Datacenter lighting',
      CoefDistribution: 100,
      CoefUnit: 3,
      Description: '',
      Formula: '',
      LocationId: 2,
      ParentId: 10,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 3,
      TrendId: 15,
    },
    {
      Id: 17,
      Name: 'IT',
      CoefDistribution: 100,
      CoefUnit: 15,
      Description: '',
      Formula: '',
      LocationId: 2,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 1,
      TrendId: 15,
    },
    {
      Id: 18,
      Name: 'Water Mtr',
      CoefDistribution: 100,
      CoefUnit: 1,
      Description: '',
      Formula: '',
      LocationId: 14,
      RefFormula: '',
      RefSamplePeriod: 7,
      SourceMode: 1,
    },
    {
      Id: 19,
      Name: 'Water Mtr C1',
      CoefDistribution: 100,
      CoefUnit: 1,
      Description: '',
      Formula: '',
      ParentId: 18,
      RefFormula: '',
      RefSamplePeriod: 7,
      TrendId: 11,
    },
    {
      Id: 20,
      Name: 'Water Mtr C1.R0',
      CoefDistribution: 100,
      CoefUnit: 0.3,
      Description: '',
      Formula: '',
      ParentId: 23,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 5,
      TrendId: 11,
    },
    {
      Id: 21,
      Name: 'Water Mtr C1.R1',
      CoefDistribution: 100,
      CoefUnit: 0.7,
      Description: '',
      Formula: '',
      ParentId: 23,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 5,
      TrendId: 11,
    },
    {
      Id: 22,
      Name: 'Water Mtr C2',
      CoefDistribution: 100,
      CoefUnit: 1,
      Description: '',
      Formula: '',
      ParentId: 18,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 5,
      SourceMode: 1,
    },
    {
      Id: 23,
      Name: 'Water Mtr C2.R0',
      CoefDistribution: 100,
      CoefUnit: 1,
      Description: '',
      Formula: '',
      ParentId: 22,
      RefFormula: '',
      RefSamplePeriod: 7,
      SourceMode: 1,
    },
    {
      Id: 24,
      Name: 'Water Mtr C1.R2',
      CoefDistribution: 100,
      CoefUnit: 1,
      Description: '',
      Formula: '',
      ParentId: 22,
      RefFormula: '',
      RefSamplePeriod: 7,
      SourceMode: 1,
      Version: 4,
    },
    {
      Id: 25,
      Name: 'Water Mtr C2.R1',
      CoefDistribution: 100,
      CoefUnit: 1,
      Description: '',
      Formula: '',
      ParentId: 23,
      RefFormula: '',
      RefSamplePeriod: 7,
      SourceMode: 1,
    },
    {
      Id: 26,
      Name: 'Hall lighting',
      CoefDistribution: 100,
      CoefUnit: 0.3,
      Description: '',
      Formula: '',
      LocationId: 13,
      ParentId: 18,
      RefFormula: '',
      RefSamplePeriod: 4,
      ServiceId: 3,
      TrendId: 9,
    },
    {
      Id: 28,
      Name: 'Compteur Eau atelier',
      AlarmIds: [11],
      CoefDistribution: 100,
      CoefUnit: 1,
      Description: 'Description',
      Formula: '',
      LocationId: 229,
      ParentId: 19,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 5,
      SourceMode: 1,
      TrendId: 29,
    },
    {
      Id: 30,
      Name: 'TestMSCons',
      CoefDistribution: 100,
      CoefUnit: 1,
      Description: '',
      Formula: '',
      IsDiff: true,
      RefFormula: '',
      RefSamplePeriod: 7,
    },
    {
      Id: 32,
      Name: 'TestCalc0',
      CoefDistribution: 100,
      CoefUnit: 1,
      Description: '',
      Formula: '[Meters/Water]*([Trends/Tarif]=0)',
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 5,
      SourceMode: 2,
    },
    {
      Id: 34,
      Name: 'TestCalc1',
      CoefDistribution: 100,
      CoefUnit: 1,
      Description: '',
      Formula: '[Meters/Water]*([Trends/Tarif]=1)',
      ParentId: 32,
      RefFormula: '',
      RefSamplePeriod: 7,
      SourceMode: 2,
    },
    {
      Id: 35,
      Name: 'TestCalc2',
      CoefDistribution: 100,
      CoefUnit: 1,
      Description: '',
      Formula: '[Locations/Site 1\\Batiment 1|Eclairage]',
      HasError: true,
      ParentId: 32,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 3,
      SourceMode: 2,
    },
    {
      Id: 39,
      Name: 'Bâtiment 5 - Jeunes adolescents - Hippodrome/GasCons',
      CoefDistribution: 100,
      CoefUnit: 1,
      Description: '',
      Formula: '',
      RefSamplePeriod: 7,
    },
    {
      Id: 40,
      Name: 'Rack1_Pdu1_Energy',
      CoefDistribution: 100,
      CoefUnit: 1,
      LocationId: 13,
      RefFormula: '',
      RefSamplePeriod: 7,
      TrendId: 1,
    },
    {
      Id: 41,
      Name: 'TestNeg',
      CoefDistribution: 100,
      CoefUnit: 1,
      RefFormula: '',
      RefSamplePeriod: 7,
      TrendId: 126,
    },
    {
      Id: 42,
      Name: 'agicfdt:1034915',
      CoefDistribution: 100,
      CoefUnit: 1,
      RefSamplePeriod: 7,
      ServiceId: 5,
      TrendId: 128,
    },
    {
      Id: 43,
      Name: 'agicfdt:1110082',
      CoefDistribution: 100,
      CoefUnit: 1,
      ParentId: 39,
      RefSamplePeriod: 7,
      ServiceId: 5,
      TrendId: 129,
    },
    {
      Id: 44,
      Name: 'Tendance Etendue Compteur Elec 1 TGBT Bâtiment A',
      CoefDistribution: 100,
      CoefUnit: 1,
      RefSamplePeriod: 7,
    },
    {
      Id: 45,
      Name: 'EauTest',
      CoefDistribution: 100,
      CoefUnit: 1,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 13,
      TrendId: 139,
    },
    {
      Id: 48,
      Name: 'TestSdel',
      CoefDistribution: 100,
      CoefUnit: 1,
      ParentId: 45,
      RefFormula: '',
      RefSamplePeriod: 7,
      TrendId: 143,
    },
    {
      Id: 49,
      Name: 'TestSdelEF',
      CoefDistribution: 100,
      CoefUnit: 1,
      ParentId: 45,
      RefFormula: '',
      RefSamplePeriod: 7,
      TrendId: 144,
    },
    {
      Id: 50,
      Name: 'YearDays',
      CoefDistribution: 100,
      CoefUnit: 1,
      RefFormula: '',
      RefSamplePeriod: 7,
      TrendId: 145,
    },
    {
      Id: 51,
      Name: 'RandomMeter',
      CoefDistribution: 100,
      CoefUnit: 1,
      ParentId: 50,
      RefFormula: '',
      RefSamplePeriod: 7,
      TrendId: 147,
    },
    {
      Id: 52,
      Name: 'P',
      CoefDistribution: 100,
      CoefUnit: 1,
      IsDiff: true,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 15,
      TrendId: 157,
    },
    {
      Id: 53,
      Name: 'F001 - Ilot J1A - SAO-10BICL20Os11S2_SS1 J1A Temp Exterieure',
      CoefDistribution: 100,
      CoefUnit: 1,
      RefSamplePeriod: 7,
    },
    {
      Id: 54,
      Name: 'TestPCVue_TREND.SIMUL.VAR1',
      CoefDistribution: 100,
      CoefUnit: 1,
      RefSamplePeriod: 7,
      TrendId: 168,
    },
    {
      Id: 55,
      Name: 'LW8 proto - 66C1/Meter index 1',
      CoefDistribution: 100,
      CoefUnit: 0.0025,
      RefFormula: '',
      RefSamplePeriod: 7,
    },
    {
      Id: 56,
      Name: 'LW8 proto - 66C1/Meter index 2',
      CoefDistribution: 100,
      CoefUnit: 0.001667,
      RefFormula: '',
      RefSamplePeriod: 7,
    },
    {
      Id: 57,
      Name: 'Compteur 1',
      CoefDistribution: 100,
      CoefUnit: 1,
      LocationId: 14,
      ParentId: 42,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 3,
      TrendId: 186,
    },
    {
      Id: 58,
      Name: 'Bat2N1Ecl',
      CoefDistribution: 100,
      CoefUnit: 1,
      LocationId: 237,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 3,
      TrendId: 9,
    },
    {
      Id: 59,
      Name: 'Bat2N2Ecl',
      CoefDistribution: 100,
      CoefUnit: 0.8,
      LocationId: 238,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 3,
      TrendId: 9,
    },
    {
      Id: 60,
      Name: 'Bat2N1PC',
      CoefDistribution: 100,
      CoefUnit: 0.3,
      LocationId: 237,
      ParentId: 59,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 17,
      TrendId: 9,
    },
    {
      Id: 61,
      Name: 'Bat2N2PC',
      CoefDistribution: 100,
      CoefUnit: 0.2,
      LocationId: 238,
      ParentId: 59,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 17,
      TrendId: 9,
    },
    {
      Id: 62,
      Name: 'Bat2N1Vent',
      CoefDistribution: 100,
      CoefUnit: 0.1,
      LocationId: 237,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 18,
      TrendId: 9,
    },
    {
      Id: 63,
      Name: 'Bat2N2Vent',
      CoefDistribution: 100,
      CoefUnit: 0.08,
      LocationId: 238,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 18,
      TrendId: 9,
    },
    {
      Id: 64,
      Name: 'Cpt1',
      CoefDistribution: 100,
      CoefUnit: 1,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 14,
      TrendId: 194,
    },
    {
      Id: 65,
      Name: 'Test manuel',
      CoefDistribution: 100,
      CoefUnit: 1,
      RefFormula: '',
      RefSamplePeriod: 7,
      SourceMode: 1,
    },
    {
      Id: 66,
      Name: 'Compteur test',
      CoefDistribution: 100,
      CoefUnit: 1,
      LocationId: 236,
      RefSamplePeriod: 7,
      ServiceId: 2,
    },
    {
      Id: 67,
      Name: 'Trend1',
      CoefDistribution: 100,
      CoefUnit: 1,
      LocationId: 1,
      RefSamplePeriod: 7,
      ServiceId: 13,
      TrendId: 204,
    },
    {
      Id: 68,
      Name: 'Eclairage bureaux',
      CoefDistribution: 100,
      CoefUnit: 0.5,
      LocationId: 15,
      ParentId: 66,
      RefFormula: '',
      RefSamplePeriod: 4,
      ServiceId: 3,
      TrendId: 9,
    },
    {
      Id: 69,
      Name: 'Eclairage RC',
      CoefDistribution: 100,
      CoefUnit: 0.5,
      LocationId: 14,
      RefSamplePeriod: 4,
      ServiceId: 3,
      TrendId: 10,
    },
    {
      Id: 70,
      Name: 'Eau',
      CoefDistribution: 100,
      CoefUnit: 0.01,
      LocationId: 13,
      RefSamplePeriod: 4,
      ServiceId: 5,
      TrendId: 11,
    },
    {
      Id: 71,
      Name: 'Chauffage',
      CoefDistribution: 100,
      CoefUnit: 1,
      LocationId: 13,
      RefFormula: '',
      RefSamplePeriod: 4,
      ServiceId: 2,
      TrendId: 12,
    },
    {
      Id: 72,
      Name: 'Climatisation',
      CoefDistribution: 100,
      CoefUnit: 1,
      LocationId: 13,
      RefSamplePeriod: 4,
      ServiceId: 6,
      TrendId: 13,
    },
    {
      Id: 73,
      Name: 'Perte',
      CoefDistribution: 100,
      CoefUnit: 1,
      Formula: '[Meters/Office lighting]-[Meters/Basement lighting]',
      RefFormula: '',
      RefSamplePeriod: 7,
      SourceMode: 2,
    },
    {
      Id: 74,
      Name: 'Cpt résiduel',
      CoefDistribution: 100,
      CoefUnit: 1,
      Formula:
        '[Meters/Office lighting] - ([Meters/Basement lighting]+ [Meters/Office lighting])',
      RefFormula: '',
      RefSamplePeriod: 7,
      SourceMode: 2,
    },
    {
      Id: 75,
      Name: 'TestBapi',
      CoefDistribution: 100,
      CoefUnit: 1,
      RefFormula: '',
      RefSamplePeriod: 7,
      TrendId: 213,
    },
    {
      Id: 76,
      Name: 'PowerElec6/ActiveEnergy_1_1',
      CoefDistribution: 100,
      CoefUnit: 1,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 14,
      TrendId: 214,
    },
    {
      Id: 77,
      Name: 'Bat3 Elec',
      CoefDistribution: 100,
      CoefUnit: 1,
      LocationId: 241,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 14,
      TrendId: 15,
    },
    {
      Id: 78,
      Name: 'Bat3 Ecl',
      CoefDistribution: 100,
      CoefUnit: 0.5,
      LocationId: 241,
      ParentId: 77,
      RefFormula: '',
      RefSamplePeriod: 7,
      ServiceId: 3,
      TrendId: 9,
    },
    {
      Id: 79,
      Name: 'TestManu',
      CoefDistribution: 100,
      CoefUnit: 1,
      IsDiff: true,
      RefFormula: '',
      RefSamplePeriod: 7,
      SourceMode: 1,
    },
    {
      Id: 80,
      Name: 'Chauffage',
      CoefDistribution: 100,
      CoefUnit: 1,
      LocationId: 1,
      RefSamplePeriod: 7,
      TrendId: 12,
      Version: 1,
    },
  ]

  files2!: TreeNode[]
  cols!: any[]
  result: any = []

  body: any
  constructor(private genericService: GenericService) {}

  ngOnInit(): void {
    this.genericService.getCounter().subscribe((result) => {
      this.result = result
      let output: any = []
      this.result.forEach((element, key) => {
        !element.ParentId
          ? output.push({
              data: { Id: element['Id'], Name: element.Name },
              children: this.getChildren(element['Id'], this.result),
            }) && this.result.splice(key, 1)
          : null
      })

      this.body = { data: output }
      this.files2 = this.body.data
      this.body.data.forEach((element) => {
        !element['children'].length ? delete element['children'] : null
      })
    })
  }

  getChildren(id: number, data: any): any {
    let children: any = []

    this.result.forEach((element, key) => {
      if (element['ParentId'] === id) {
        let kids = this.getChildren(element['Id'], data)
        !kids.length
          ? children.push({
              data: { Id: element.Id, Name: element.Name },
            }) && data.splice(key, 1)
          : children.push({
              data: { Id: element.Id, Name: element.Name },
              children: kids,
            }) && data.splice(key, 1)
      }
    })

    return children
  }
}
